version: "3.9"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:5432
    environment: 
      - POSTGRES_USER={{POSTGRES_USER}}
      - POSTGRES_PASSWORD={{POSTGRES_PASSWORD}}
      - POSTGRES_DB={{POSTGRES_PASSWORD}}
    volumes: 
      - pgdata:/data/postgres
    networks:
      app_net:
        ipv4_address: 172.16.238.10

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    networks:
      app_net:
        ipv4_address: 172.16.238.08

  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      app_net:
        ipv4_address: 172.16.238.09
    depends_on: 
      - database_ignite
      - redis

volumes: 
  pgdata:
    driver: local

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
        - subnet: "2001:3984:3989::/64"
